electronic_library/apps/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('create/category/', views.CategoryCreateView.as_view(), name='category_create'),
    path('edit/category/<int:pk>/', views.CategoryEditView.as_view(), name='category_edit'),
    path('delete/category/<int:pk>', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('show/category/<int:pk>/', views.CategoryDetailView.as_view(), name='category'),
    path('show/categories/', views.CategoryListView.as_view(), name='category_list'),

    path('create/author/', views.AuthorCreateView.as_view(), name='author_create'),
    path('edit/author/<int:pk>/', views.AuthorEditView.as_view(), name='author_edit'),
    path('delete/author/<int:pk>', views.AuthorDeleteView.as_view(), name='author_delete'),
    path('show/author/<int:pk>/', views.AuthorDetailView.as_view(), name='author'),
    path('show/authors/', views.AuthorListView.as_view(), name='author_list'),

    path('create/book/', views.BookCreateView.as_view(), name='book_create'),
    path('edit/book/<int:pk>/', views.BookEditView.as_view(), name='book_edit'),
    path('delete/book/<int:pk>', views.BookDeleteView.as_view(), name='book_delete'),
    path('show/book/<int:pk>/', views.BookDetailView.as_view(), name='book'),
    path('show/books/', views.BookListView.as_view(), name='book_list'),
    path('show/books/filter/', views.BookListFilter.as_view(), name='book_list_filter'),

    path('reservation/<int:pk>/', views.ReaderReservationView.as_view(), name='reservation'),
    path('show/reservations/', views.ReaderReservationList.as_view(), name='reservation_list'),
    path('show/reservation/<int:pk>/', views.ReaderReservationDetail.as_view(), name='reservation_detail'),
    path('show/admin/reservations/', views.AdminReservationList.as_view(), name='reservation_list_admin'),
    path('reservation/give_out/<int:pk>/', views.AdminReservationIssued.as_view(), name='reservation_give_out'),
    path('reservation/return/<int:pk>/', views.AdminReservationReturned.as_view(), name='reservation_returned'),
    path('reservation/search/', views.ReservationListFilter.as_view(), name='reservation_filter'),
]

electronic_library/electronic_library/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from . import errors

urlpatterns = [
    path('', views.home, name='home'),

    path('books/', include('books.urls')),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('accounts/', include('users.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler400 = errors.handle_bad_request
handler403 = errors.handle_bad_permission
handler404 = errors.handle_page_not_found
handler500 = errors.handle_server_error

electronic_library/apps/books/forms.py
from pytz import timezone
from datetime import datetime, timedelta


from django import forms
from django.core.exceptions import NON_FIELD_ERRORS

from .models import Category, Author, Book, Reservation
from electronic_library.settings import TIME_ZONE
from .validators import RangeDateTime


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        error_messages = {
            'name': {
                'unique': 'Категория с таким названием уже существует.'
            }
        }


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'surname', 'patronymic', 'birthday']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': 'Такой автор уже есть в БД.'
            }
        }

    def get_date(self):
        if self.instance:
            return self.instance.birthday.strftime('%Y-%m-%d')
        return ''


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class ReaderReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['book', 'date_start', 'date_end']


class ReservationForm(forms.Form):
    date_start = forms.DateTimeField(required=True)
    date_end = forms.DateTimeField(required=True)

    def clean_date_start(self):
        date_start = self.cleaned_data.get('date_start')
        start = datetime.now(timezone(TIME_ZONE))
        end = start + timedelta(days=1)
        RangeDateTime(start, end)(date_start)
        return date_start

    def clean_date_end(self):
        date_end = self.cleaned_data.get('date_end')
        start = self.cleaned_data.get('date_start')
        RangeDateTime(start)(date_end)
        return date_end

electronic_library/apps/books/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from django.views.generic.base import View
from django.db.models import Q

from .models import Book, Category, Author, Reservation
from electronic_library.mixins import OnlyAdmin
from .forms import CategoryForm, AuthorForm, BookForm, ReservationForm


@method_decorator(login_required, 'dispatch')
class CategoryCreateView(OnlyAdmin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'books/category_create.html'

    def get_success_url(self):
        messages.success(self.request, 'Категория успешно добавлена!')
        return reverse_lazy('books:category', args=[self.object.id])


@method_decorator(login_required, 'dispatch')
class CategoryEditView(OnlyAdmin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'books/category_edit.html'

    def get_success_url(self):
        messages.success(self.request, 'Категория успешно отредактирована!')
        return reverse_lazy('books:category', args=[self.object.id])


@method_decorator(login_required, 'dispatch')
class CategoryDeleteView(OnlyAdmin, DeleteView):
    model = Category
    template_name = 'books/category_delete.html'

    def get_success_url(self):
        messages.success(self.request, 'Категория успешно удалена!')
        return reverse_lazy('books:categories')


@method_decorator(login_required, 'dispatch')
class CategoryDetailView(OnlyAdmin, DetailView):
    model = Category
    template_name = 'books/category_detail.html'


@method_decorator(login_required, 'dispatch')
class CategoryListView(OnlyAdmin, ListView):
    model = Category
    template_name = 'books/category_list.html'


@method_decorator(login_required, 'dispatch')
class AuthorCreateView(OnlyAdmin, CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'books/author_create.html'

    def get_success_url(self):
        messages.success(self.request, 'Автор успешно добавлен!')
        return reverse_lazy('books:author', args=[self.object.id])


@method_decorator(login_required, 'dispatch')
class AuthorEditView(OnlyAdmin, UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'books/author_edit.html'

    def get_success_url(self):
        messages.success(self.request, 'Автор успешно отредактирован!')
        return reverse_lazy('books:author', args=[self.object.id])


@method_decorator(login_required, 'dispatch')
class AuthorDeleteView(OnlyAdmin, DeleteView):
    model = Author
    template_name = 'books/author_delete.html'

    def get_success_url(self):
        messages.success(self.request, 'Автор успешно удален!')
        return reverse_lazy('books:author_list')


@method_decorator(login_required, 'dispatch')
class AuthorDetailView(OnlyAdmin, DetailView):
    model = Author
    template_name = 'books/author_detail.html'


@method_decorator(login_required, 'dispatch')
class AuthorListView(OnlyAdmin, ListView):
    model = Author
    template_name = 'books/author_list.html'


class BookListView(ListView):
    model = Book
    template_name = 'books/book_list.html'


class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book_detail.html'


class BookListFilter(ListView):
    model = Book
    template_name = 'books/book_list.html'

    def get_queryset(self):
        book_name = self.request.GET.get('book_name')
        query = Q(name__icontains=book_name)
        return Book.objects.filter(query)


@method_decorator(login_required, 'dispatch')
class BookCreateView(OnlyAdmin, CreateView):
    model = Book
    form_class = BookForm
    template_name = 'books/book_create.html'

    def get_success_url(self):
        messages.success(self.request, 'Книга успешно добавлена!')
        return reverse_lazy('books:book', args=[self.object.id])


@method_decorator(login_required, 'dispatch')
class BookEditView(OnlyAdmin, UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'books/book_edit.html'

    def get_success_url(self):
        messages.success(self.request, 'Книга успешно отредактирована!')
        return reverse_lazy('books:book', args=[self.object.id])


@method_decorator(login_required, 'dispatch')
class BookDeleteView(OnlyAdmin, DeleteView):
    model = Book
    template_name = 'books/book_delete.html'

    def get_success_url(self):
        messages.success(self.request, 'Книга успешно удалена!')
        return reverse_lazy('books:book_list')


@method_decorator(login_required, 'dispatch')
class ReaderReservationView(FormView):
    form_class = ReservationForm
    template_name = 'books/reservation_reader.html'
    success_url = reverse_lazy('books:book_list')

    def get(self, request, *args, **kwargs):
        pk = request.resolver_match.kwargs.get('pk')
        book = get_object_or_404(Book, pk=pk)

        if not Reservation.unique_active_reservation(request.user, book):
            messages.warning(request,
                             f'Вы уже забронировали книгу {book.name}.')
            return HttpResponseRedirect(reverse_lazy('books:book_list'))

        if book and book.in_stock() > 0:
            return super(ReaderReservationView, self).get(request, *args,
                                                          **kwargs)

        messages.warning(request, f'Книги {book.name} нет сейчас в наличии.')
        return HttpResponseRedirect(reverse_lazy('books:book_list'))

    def post(self, request, *args, **kwargs):
        pk = request.resolver_match.kwargs.get('pk')
        book = get_object_or_404(Book, pk=pk)

        if not Reservation.unique_active_reservation(request.user, book):
            messages.warning(request,
                             f'Вы уже забронировали книгу {book.name}.')
            return HttpResponseRedirect(reverse_lazy('books:book_list'))

        if book and book.in_stock() > 0:
            form = self.get_form()
            if form.is_valid():
                Reservation.objects.create(
                    book=book,
                    user=request.user,
                    date_start=form.cleaned_data.get('date_start'),
                    date_end=form.cleaned_data.get('date_end')
                )
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

        messages.warning(request, f'Книги {book.name} нет сейчас в наличии.')
        return HttpResponseRedirect(reverse_lazy('books:book_list'))


@method_decorator(login_required, 'dispatch')
class ReaderReservationList(ListView):
    model = Reservation
    template_name = 'books/reservation_list.html'

    def get_queryset(self):
        return Reservation.objects.filter(user=self.request.user)


@method_decorator(login_required, 'dispatch')
class ReaderReservationDetail(DetailView):
    model = Reservation
    template_name = 'books/reservation_detail.html'


@method_decorator(login_required, 'dispatch')
class AdminReservationList(OnlyAdmin, ListView):
    model = Reservation
    template_name = 'books/reservation_list_admin.html'

    def get_queryset(self):
        return Reservation.objects.all()


@method_decorator(login_required, 'dispatch')
class AdminReservationIssued(OnlyAdmin, View):
    """
    Выполняет смену поля received у бронирования. Используется для
    выдачи книги.
    """

    def __check_reservation(self, request, reservation, url_redirect):
        """
        Проверяет поля completed и received у бронирования, если
        книга уже выдана или возвращена, то возвращает пользователю
        соответствующие сообщение.
        """
        if reservation.completed:
            messages.warning(request,
                             f'Пользователь вернул книгу!')
            return HttpResponseRedirect(url_redirect)

        if reservation.received:
            messages.warning(request,
                             f'Книга уже выдана!')
            return HttpResponseRedirect(url_redirect)
        reservation.receive()

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        reservation = get_object_or_404(Reservation, pk=pk)
        url = reverse_lazy('books:reservation_detail', args=[int(pk)])

        self.__check_reservation(request, reservation, url)

        messages.success(request, f'Книга {reservation.book.name} выдана пользователю.')
        return HttpResponseRedirect(url)


@method_decorator(login_required, 'dispatch')
class AdminReservationReturned(OnlyAdmin, View):
    """
    Проверяет поле completed у бронирования, если книга уже
    возвращена, то возвращает сообщение пользователю.
    """

    def __check_reservation(self, request, reservation, redirect_url):
        if reservation.completed:
            messages.warning(request,
                             f'Пользователь уже вернул книгу!')
            return HttpResponseRedirect(redirect_url)
        reservation.complete()

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        reservation = get_object_or_404(Reservation, pk=pk)
        url = reverse_lazy('books:reservation_detail', args=[int(pk)])

        self.__check_reservation(request, reservation, url)
        messages.success(request, f'Книга {reservation.book.name} возвращена пользователем.')
        return HttpResponseRedirect(url)


@method_decorator(login_required, 'dispatch')
class ReservationListFilter(OnlyAdmin, ListView):
    model = Reservation
    template_name = 'books/reservation_list_admin.html'

    def get_queryset(self):

electronic_library/templates/books/author_create.html
{% extends "home.html" %}

{% block title %}Автор{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="form-signin shadow-lg bg-white">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <p class="h3 mb-3 fw-normal text-center">Добавление автора</p>
            <div class="mb-3">
                <label class="form-label" for="{{ form.name.id_for_label }}">Имя</label>
                <input type="text" id="{{form.name.id_for_label}}" name="{{form.name.name}}"
                class="form-control" aria-describedby="nameHelp">
                {% if form.name.errors %}
                    <div class="form-text" id="nameHelp">
                        {% for error in form.name.errors %}
                            <p class="text-danger m-0">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label class="form-label" for="{{ form.surname.id_for_label }}">Фамилия</label>
                <input type="text" id="{{form.surname.id_for_label}}" name="{{form.surname.name}}"
                class="form-control" aria-describedby="surnameHelp">
                {% if form.surname.errors %}
                    <div class="form-text" id="surnameHelp">
                        {% for error in form.surname.errors %}
                            <p class="text-danger m-0">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label class="form-label" for="{{ form.patronymic.id_for_label }}">Отчество</label>
                <input type="text" id="{{form.patronymic.id_for_label}}" name="{{form.patronymic.name}}"
                class="form-control" aria-describedby="patronymicHelp">
                {% if form.patronymic.errors %}
                    <div class="form-text" id="patronymicHelp">
                        {% for error in form.patronymic.errors %}
                            <p class="text-danger m-0">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label class="form-label" for="{{ form.birthday.id_for_label }}">Дата рождения</label>
                <input type="date" id="{{form.birthday.id_for_label}}" name="{{form.birthday.name}}"
                class="form-control" aria-describedby="birthdayHelp">
                {% if form.birthday.errors %}
                    <div class="form-text" id="birthdayHelp">
                        {% for error in form.birthday.errors %}
                            <p class="text-danger m-0">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <button type="submit" class="w-100 btn btn-primary">Добавить</button>
        </form>
    </div>
</div>
{% endblock %}

electronic_library/templates/books/author_edit.html
{% extends "home.html" %}

{% block title %}Автор{% endblock %}

{% block content %}
<div class="container">
    <div class="form-signin shadow-lg border border-2 rounded bg-white p-3 mt-3">
        <form action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p class="h4 mb-3 fw-normal text-center">Редактирование автора</p>
        <div class="mb-3 col">
            <label class="form-label" for="{{ form.name.id_for_label }}">Имя</label>
            <input type="text" id="{{form.name.id_for_label}}"
            name="{{form.name.name}}" value="{{form.name.value}}"
            aria-describedby="nameHelp" class="form-control">
            {% if form.name.errors %}
                <div id="nameHelp" class="form-text">
                    {% for error in form.name.errors %}
                        <p>{{ error|escape }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="mb-3 col">
            <label class="form-label" for="{{ form.surname.id_for_label }}">Фамилия</label>
            <input type="text" id="{{form.surname.id_for_label}}"
            name="{{form.surname.name}}" value="{{form.surname.value}}"
            aria-describedby="surnameHelp" class="form-control">
            {% if form.surname.errors %}
                <div id="surnameHelp" class="form-text">
                    {% for error in form.surname.errors %}
                        <p>{{ error|escape }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="mb-3 col">
            <label class="form-label" for="{{ form.patronymic.id_for_label }}">Отчество</label>
            <input type="text" id="{{form.patronymic.id_for_label}}"
            name="{{form.patronymic.name}}" value="{{form.patronymic.value}}"
            aria-describedby="patronymicHelp" class="form-control">
            {% if form.patronymic.errors %}
                <div id="patronymicHelp" class="form-text">
                    {% for error in form.patronymic.errors %}
                        <p>{{ error|escape }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="mb-3 col">
            <label class="form-label" for="{{ form.birthday.id_for_label }}">Дата рождения</label>
            <input type="date" id="{{form.birthday.id_for_label}}"
            name="{{form.birthday.name}}" value="{{form.get_date}}"
            aria-describedby="birthdayHelp" class="form-control">
            {% if form.birthday.errors %}
                <div id="birthdayHelp" class="form-text">
                    {% for error in form.birthday.errors %}
                        <p>{{ error|escape }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="mb-2 w-100 btn btn-primary">Редактировать</button>
        <a href="{% url 'books:author_list' %}">К списку авторов</a>
    </form>
    </div>
</div>

{% endblock %}

electronic_library/templates/books/author_list.html
{% extends "home.html" %}

{% block title %}Авторы{% endblock %}

{% block content %}
<div class="container">
    <div class="row px-3 gx-3">
        <div class="col">
            <h3>Авторы</h3>
            <p class="mb-2">
                <a href="{% url 'books:author_create' %}" class="btn btn-sm btn-primary">Добавить</a> автора
            </p>
        </div>
        <hr class="mb-2">
    </div>
    <div class="row justify-content-center justify-content-lg-start px-3 gx-3 gy-2">
        {% for object in author_list %}
            <div class="col-12 col-lg-6">
                <div class="border border-2 rounded p-2">
                    <p class="m-0">
                        <strong>Автор:</strong> {{ object.full_name }}
                    </p>
                    <a class="link-primary" href="{% url 'books:author' object.pk %}">Подробно</a>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

electronic_library/templates/books/book_detail.html
{% extends "home.html" %}

{% block title %}Книга{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-7">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Книга</h3>  
                    <div>
                        <p class="card-text"><strong>Название:</strong> {{ object.name }}</p>
                        <p class="card-text"><strong>Категория:</strong> {{ object.category.name }}</p>
                        <p>Авторы:
                            <ul>
                            {% for author in object.authors.all %}
                                <li>{{author.full_name}}</li>
                            {% endfor %}
                            </ul>
                        </p>
                        <p class="card-text"><strong>Описание:</strong> {{ object.description }}</p>
                        <p class="card-text"><strong>Издательство:</strong> {{ object.publisher }}</p>
                        <p class="card-text"><strong>Год издания:</strong> {{ object.publishing_date }} г.</p>
                        <p class="card-text"><strong>Количество:</strong> {{ object.count }} шт.</p>
                        <p class="card-text"><strong>В наличии:</strong> {{ object.in_stock }} шт.</p>
                        {% if object.in_stock > 0 %}
                            <a class="card-link" href="{% url 'books:reservation' object.pk %}">Забронировать</a>
                        {% endif %}
                        {% if user.is_staff %}
                            <a class="card-link" href="{% url 'books:book_list' %}">К списку книг</a>
                            <a class="card-link" href="{% url 'books:book_edit' object.pk %}">Редактировать книгу</a>
                            <a class="card-link" href="{% url 'books:book_delete' object.pk %}">Удалить книгу</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

electronic_library/templates/books/category_delete.html
{% extends "home.html" %}

{% block title %}Категория{% endblock %}

{% block content %}
<div class="container p-3">
    <div class="alert alert-danger mt-3" role="alert">
        <h4 class="alert-heading">Удаление категории</h4>
        <p><strong>Вы уверены, что хотите удалить категорию:</strong> {{ object.name }}?</p>
        <hr>
        <form action="{% url 'books:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
</div>
{% endblock %}

electronic_library/templates/books/category_edit.html
{% extends "home.html" %}

{% block title %}Категория{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <div class="shadow-lg border border-2 rounded bg-white p-3 mt-3"
    style="max-width: 24rem;">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <p class="h4 mb-3 fw-normal text-center">Редактирование категории</p>
            <div class="mb-3 col">
                <label for="{{ form.name.id_for_label }}" class="form-label">Название категории</label>
                <input type="text" id="{{form.name.id_for_label}}" name="{{form.name.name}}" value="{{form.name.value}}"
                aria-describedby="nameHelp" class="form-control">
                {% if form.name.errors %}
                <div id="nameHelp" class="form-text">
                    {% for error in form.name.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <button type="submit" class="w-100 btn btn-primary">Редактировать</button>
        </form>
    </div>
</div>
{% endblock %}

electronic_library/templates/books/category_list.html
{% extends "home.html" %}

{% block title %}Категории{% endblock %}

{% block content %}
<div class="container">
    <div class="row px-3 gx-3">
        <div class="col">
            <h3>Категории</h3>
            <p class="mb-2">
                <a href="{% url 'books:category_create' %}" class="btn btn-sm btn-primary">Добавить</a> категорию
            </p>
        </div>
        <hr class="mb-2">
    </div>
    <div class="row justify-content-center justify-content-lg-start px-3 gx-3 gy-2">
        {% for object in category_list %}
            <div class="col-12 col-lg-6">
                <div class="border border-2 rounded p-2">
                    <p class="m-0">
                        <strong>Название категории:</strong> {{ object.name }}
                    </p>
                    <a href="{% url 'books:category' object.pk %}"
                    class="link-primary">
                        Подробно
                    </a>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

electronic_library/templates/books/reser_pattern_list.html
{% if user.is_staff %}
    {% if not object.completed %}
        {% if object.received %}
            <p class="card-text alert-info">Пользователь забрал книгу.</p>
        {% else %}
            <p class="card-text alert-warning">Пользователь не забрал книгу.</p>
        {% endif %}
    {% else %}
        <p class="card-text alert-info">Пользователь вернул книгу.</p>
    {% endif %}
{% else %}
    {% if not object.completed %}
        {% if object.received %}
            <p class="card-text alert-info">Вы забрали книгу.</p>
        {% else %}
            <p class="card-text alert-warning">Вы не забрали книгу.</p>
        {% endif %}
    {% else %}
        <p class="card-text alert-info">Вы вернули книгу.</p>
    {% endif %}
{% endif %}

electronic_library/templates/books/reservation_list.html
{% extends "home.html" %}

{% block title %}Бронирование{% endblock %}

{% block content %}
<div class="container">
    <div class="row px-3 gx-3">
        <div class="col">
            <h3>Ваши бронирования книг</h3>
            {% if user.is_staff %}
            <p><a href="{% url 'books:reservation_list_admin' %}">Перейти</a> к списку бронирований всех пользователей.</p>
            {% endif %}
        </div>
        <hr class="mb-2">
    </div>
    <div class="row justify-content-center justify-content-lg-start px-3 gx-3 gy-2">
        {% for object in reservation_list %}
            <div class="col-12 col-lg-6">
                <div class="border border-2 rounded p-2">
                    <p class="m-0">
                        <strong>Книга:</strong> {{ object.book.name }}
                    </p>
                    {% include "books/reser_pattern_list.html" %}
                    <a href="{% url 'books:reservation_detail' object.pk %}"
                    class="link-primary">
                        Подробно
                    </a>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

electronic_library/templates/books/reservation_list_admin.html
{% extends "home.html" %}

{% block title %}Бронирование{% endblock %}

{% block content %}
<div class="container">
    <div class="row px-3 gx-3">
        <div class="col-12">
            <h3>Бронирования книг всех пользователей</h3>
        </div>
        <div class="col-8">
            <form action="{% url 'books:reservation_filter' %}" method="get" class="d-flex">
                <input type="text" name="book_name" class="form-control me-2"
                       placeholder="Поиск по названию книги">
                <input type="text" name="username" class="form-control me-2"
                       placeholder="Поиск по имени пользователя">
                <button type="submit" class="btn btn-outline-success">Поиск</button>
            </form>
            <br>
        </div>
        <hr class="mb-2">
    </div>
    <div class="row justify-content-center justify-content-lg-start px-3 gx-3 gy-2">
        {% for object in reservation_list %}
            <div class="col-12 col-lg-6">
                <div class="border border-2 rounded p-2">
                    <p class="m-0">
                        <strong>Книга:</strong> {{ object.book.name }}
                    </p>
                    <p class="m-0">Пользователь: {{ object.user.username }}</p>
                    {% include "books/reser_pattern_list.html" %}
                    <a href="{% url 'books:reservation_detail' object.pk %}"
                    class="link-primary">
                        Подробно
                    </a>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

electronic_library/templates/books/reservation_pattern.html
{% if not object.completed %}
    {% if object.received %}
        {% if not user.is_staff %}
            <p class="card-text alert-info">Вы забрали книгу.</p>
        {% else %}
            <p class="card-text alert-info">Книга выдана пользователю</p>
            <a class="card-link"
                href="{% url 'books:reservation_returned' object.pk %}">Вернуть</a>
        {% endif %}
    {% else %}
        {% if not user.is_staff %}
            <p class="card-text alert-warning">Вы не забрали книгу.</p>
        {% else %}
            <p class="card-text alert-warning">Книга не выдана пользователю</p>
            <a class="card-link"
                href="{% url 'books:reservation_give_out' object.pk %}">Выдать</a>
        {% endif %}
    {% endif %}
{% else %}
    {% if not user.is_staff %}
        <p class="card-text alert-info">Вы вернули книгу.</p>
    {% else %}
        <p class="card-text alert-info">Пользователь вернул книгу.</p>
    {% endif %}
{% endif %}