electronic_library/apps/users/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('edit/profile/<int:pk>/', views.UserEditView.as_view(), name='user_edit'),
]

electronic_library/electronic_library/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from . import errors

urlpatterns = [
    path('', views.home, name='home'),

    path('books/', include('books.urls')),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('accounts/', include('users.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler400 = errors.handle_bad_request
handler403 = errors.handle_bad_permission
handler404 = errors.handle_page_not_found
handler500 = errors.handle_server_error

electronic_library/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    email = models.EmailField(verbose_name='Почта',
                              blank=False, unique=True)
    patronymic = models.CharField(max_length=50,
                                  verbose_name='Отчество',
                                  blank=True, default='')
    birthday = models.DateField(verbose_name='Дата рождения',
                                blank=True, null=True, default=None)
    residence_place = models.CharField(max_length=512,
                                       verbose_name='Место проживания',
                                       blank=True, default='')
    work_study_place = models.CharField(max_length=512,
                                        verbose_name='Место учебы/работы',
                                        blank=True, default='')

    def full_name(self):
        return f'{self.first_name} {self.last_name} {self.patronymic}'

    def __str__(self):
        return str(self.id) + ': ' + self.username

electronic_library/apps/users/forms.py
from django import forms

from .models import User


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'patronymic', 'birthday', 'residence_place',
                  'work_study_place', 'email']
        error_messages = {
                'username': {
                    'invalid': 'Введите правильное имя пользователя. ' \
                    'Оно может содержать только буквы, цифры и знаки ' \
                    '@.+-_',
                },
                'email': {
                    'unique': 'На данную почту уже ' \
                    'зарегистрирован пользователь.'
                }
        }

electronic_library/apps/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic.base import TemplateView

from electronic_library.mixins import *
from .models import User
from .forms import EditProfileForm


class UserProfileView(TemplateView):
    template_name = 'users/user_profile.html'


class UserEditView(OnlyUserMixin, UpdateView):
    model = User
    form_class = EditProfileForm
    template_name = 'users/user_edit.html'

    def get_success_url(self):
        return reverse_lazy('accounts:profile')

electronic_library/templates/users/user_edit.html
{% extends "home.html" %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="container">
    <div class="shadow-lg border border-2 rounded bg-white p-3 mt-3">
        <p class="h4 mb-3 fw-normal text-center">Редактирование профиля</p>
        <form action="" method="post"
        class="row row-cols-1 row-cols-lg-2 justify-content-center gx-3 p-2">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3 col">
                <label for="{{ form.username.id_for_label }}" class="form-label">Логин</label>
                <input type="text" id="{{ form.username.id_for_label }}"
                name="{{ form.username.name }}" class="form-control"
                value="{{ form.username.value }}" aria-describedby="usernameHelp">
                {% if form.username.errors %}
                <div id="usernameHelp" class="form-text">
                    {% for error in form.username.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                <input type="text" id="{{ form.first_name.id_for_label }}"
                name="{{ form.first_name.name }}" class="form-control"
                value="{{ form.first_name.value }}" aria-describedby="first_nameHelp">
                {% if form.first_name.errors %}
                <div id="first_nameHelp" class="form-text">
                    {% for error in form.first_name.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                <input type="text" id="{{ form.last_name.id_for_label }}"
                name="{{ form.last_name.name }}" class="form-control"
                value="{{ form.last_name.value }}" aria-describedby="last_nameHelp">
                {% if form.last_name.errors %}
                <div id="last_nameHelp" class="form-text">
                    {% for error in form.last_name.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label for="{{ form.patronymic.id_for_label }}" class="form-label">Отчество</label>
                <input type="text" id="{{ form.patronymic.id_for_label }}"
                name="{{ form.patronymic.name }}" class="form-control"
                value="{{ form.patronymic.value }}" aria-describedby="patronymicHelp">
                {% if form.patronymic.errors %}
                <div id="patronymicHelp" class="form-text">
                    {% for error in form.patronymic.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label class="form-label" for="{{ form.birthday.id_for_label  }}">Дата рождения</label>
                <input type="date" id="{{ form.birthday.id_for_label }}"
                name="{{ form.birthday.name }}" class="form-control"
                value="{{ form.birthday.value }}" aria-describedby="birthdayHelp">
                {% if form.birthday.errors %}
                <div id="birthdayHelp" class="form-text">
                    {% for error in form.birthday.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label class="form-label" for="{{ form.residence_place.id_for_label  }}">Место проживания</label>
                <input type="text" id="{{ form.residence_place.id_for_label }}"
                name="{{ form.residence_place.name }}" class="form-control"
                value="{{ form.residence_place.value }}" aria-describedby="residence_placeHelp">
                {% if form.residence_place.errors %}
                <div id="residence_placeHelp" class="form-text">
                    {% for error in form.residence_place.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label class="form-label" for="{{ form.work_study_place.id_for_label }}">Место учебы работы</label>
                <input type="text" id="{{ form.work_study_place.id_for_label }}"
                name="{{ form.work_study_place.name }}" class="form-control"
                value="{{ form.work_study_place.value }}" aria-describedby="work_study_placeHelp">
                {% if form.work_study_place.errors %}
                <div id="work_study_placeHelp" class="form-text">
                    {% for error in form.work_study_place.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="mb-3 col">
                <label for="{{ form.email.id_for_label }}" class="form-label">Почта</label>
                <input type="text" id="{{ form.email.id_for_label }}"
                name="{{ form.email.name }}" class="form-control"
                value="{{ form.email.value }}" aria-describedby="emailHelp">
                {% if form.email.errors %}
                <div id="emailHelp" class="form-text">
                    {% for error in form.email.errors %}
                        <p class="text-danger m-0">{{ error|escape }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="col">
                <button class="w-100 btn btn-primary" type="submit">Редактировать</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

electronic_library/templates/users/user_profile.html
{% extends "home.html" %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="card shadow-lg mt-3" style="max-width: 24rem;">
            <div class="card-body">
                <h5 class="card-title">Профиль</h5>
                <p>Логин: {{ request.user.username }}</p>
                <p>Имя: {{ request.user.first_name }}</p>
                <p>Фамилия: {{ request.user.last_name }}</p>
                <p>Отчество: {{ request.user.patronymic }} </p>
                {% if request.user.birthday %}
                    <p>Дата рождения: {{ request.user.birthday }}</p>
                {% else %}
                    <p>Дата рождения: не указана</p>
                {% endif %}
                <p>Место проживания: {{ request.user.residence_place }}</p>
                <p>Место учебы/работы: {{ request.user.work_study_place }}</p>
                <p>Почта: {{ request.user.email }}</p>
                <a class="card-link"
                href="{% url 'accounts:user_edit' request.user.pk %}">
                    Редактировать профиль
                </a>
                <a class="card-link"
                href="{% url 'password_change' %}">
                    Сменить пароль
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}