electronic_library/apps/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('create/category/', views.CategoryCreateView.as_view(), name='category_create'),
    path('edit/category/<int:pk>/', views.CategoryEditView.as_view(), name='category_edit'),
    path('delete/category/<int:pk>', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('show/category/<int:pk>/', views.CategoryDetailView.as_view(), name='category'),
    path('show/categories/', views.CategoryListView.as_view(), name='category_list'),

    path('create/author/', views.AuthorCreateView.as_view(), name='author_create'),
    path('edit/author/<int:pk>/', views.AuthorEditView.as_view(), name='author_edit'),
    path('delete/author/<int:pk>', views.AuthorDeleteView.as_view(), name='author_delete'),
    path('show/author/<int:pk>/', views.AuthorDetailView.as_view(), name='author'),
    path('show/authors/', views.AuthorListView.as_view(), name='author_list'),

    path('create/book/', views.BookCreateView.as_view(), name='book_create'),
    path('edit/book/<int:pk>/', views.BookEditView.as_view(), name='book_edit'),
    path('delete/book/<int:pk>', views.BookDeleteView.as_view(), name='book_delete'),
    path('show/book/<int:pk>/', views.BookDetailView.as_view(), name='book'),
    path('show/books/', views.BookListView.as_view(), name='book_list'),
    path('show/books/filter/', views.BookListFilter.as_view(), name='book_list_filter'),

    path('reservation/<int:pk>/', views.ReaderReservationView.as_view(), name='reservation'),
    path('show/reservations/', views.ReaderReservationList.as_view(), name='reservation_list'),
    path('show/reservation/<int:pk>/', views.ReaderReservationDetail.as_view(), name='reservation_detail'),
    path('show/admin/reservations/', views.AdminReservationList.as_view(), name='reservation_list_admin'),
    path('reservation/give_out/<int:pk>/', views.AdminReservationIssued.as_view(), name='reservation_give_out'),
    path('reservation/return/<int:pk>/', views.AdminReservationReturned.as_view(), name='reservation_returned'),
    path('reservation/search/', views.ReservationListFilter.as_view(), name='reservation_filter'),
]

electronic_library/apps/users/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('edit/profile/<int:pk>/', views.UserEditView.as_view(), name='user_edit'),
]

electronic_library/electronic_library/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from . import errors

urlpatterns = [
    path('', views.home, name='home'),

    path('books/', include('books.urls')),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('accounts/', include('users.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler400 = errors.handle_bad_request
handler403 = errors.handle_bad_permission
handler404 = errors.handle_page_not_found
handler500 = errors.handle_server_error

electronic_library/templates/home.html
{% load static %}

<!doctype html>
<html class="h-100" lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Электронная библиотека{% endblock %}</title>
  </head>
  <body class="d-flex flex-column h-100">
    <script defer src="{% static 'js/toast_show.js' %}" ></script>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                      data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                      aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'books:book_list' %}" class="nav-link">Библиотека</a>
                    </li>
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'books:reservation_list' %}" class="nav-link">Бронирования</a>
                    </li>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a href="{% url 'books:category_list' %}" class="nav-link">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'books:author_list' %}" class="nav-link">Авторы</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'accounts:profile' %}" class="nav-link">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="nav-link">Выйти</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a href="{% url 'register' %}" class="nav-link">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">Войти</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
        </nav>    
    </header>
    
    <main class="flex-shrink-0 position-relative">
        {% if messages %}
        <!-- Position it -->
        <div class="toast-container position-absolute top-0 end-0 p-3"
        style="max-height:  80vh; z-index: 100;">
            <!-- Then put toasts within -->
            {% for message in messages %}
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="10000">
              <div class="toast-header">
                <strong class="me-auto">Уведомление</strong>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
              </div>
              <div class="toast-body">
                {{ message }}
              </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% block content %}{% endblock %}
    </main>

    <footer class="mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">Электронная библиотека - 2021</span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>